### ISSUE TITLE
Overflow and path error on Windows

### ISSUE THREAD

**Issue by desmondCTNG** [retroplasma/flyover-reverse-engineering#11]
I am in Windows with GO 1.15, I changed the config.json file and executed the go get instruction. When I ran ```cd "$(go env GOPATH)/src/github.com/retroplasma/flyover-reverse-engineering"```, the system cannot find the path specified is reported. I neglected it and ran the example code in README.md to get Santa Monica Pier, then I get :
``# github.com/retroplasma/flyover-reverse-engineering/pkg/fly/c3m/internal
..\..\..\go\src\github.com\retroplasma\flyover-reverse-engineering\pkg\fly\c3m\internal\huffman.go:148:35: constant 4294967295 overflows int``

Is there any advice about the overflow and the path problem?

**Comment by retroplasma** [comment]
Are you using Ubuntu on WSL2 on Windows 10 on a 64-bit machine?

It's the only Windows setup I tried, but it worked for me. The app looked like this:
<img width="50px" src="https://user-images.githubusercontent.com/46618410/122551485-90b34580-d024-11eb-8aeb-1633bea6c87d.png"> <img width="50px" src="https://user-images.githubusercontent.com/46618410/122552136-7463d880-d025-11eb-8914-828dfdabf0ff.png">
