### ISSUE TITLE
no Go files in /$GOPATH/src/github.com/retroplasma/flyover-reverse-engineering

### ISSUE THREAD

**Issue by bydesign** [retroplasma/flyover-reverse-engineering#2]
That's the error I get when running:
go get github.com/retroplasma/flyover-reverse-engineering

I just downloaded go today so I'm using the latest version. I noticed there is no go file in the root, is that related?

**Comment by retroplasma** [comment]
Oh, this is something that was fine with an older go version. There is no go file in root indeed. You should still be able to `cd` there after running `go get` and use the commands from the readme. Hope that works for now. I have to look into it eventually.

**Comment by retroplasma** [comment]
Changed it to this in the readme:
```
go get -d github.com/retroplasma/flyover-reverse-engineering/...
```
