### ISSUE TITLE
panic: unexpected end of JSON input

### ISSUE THREAD

**Issue by i-syme** [retroplasma/flyover-reverse-engineering#3]
Hey,

Not entirely sure what I'm doing wrong. In terminal getting a panic: unexpected end of JSON input that seems to be coming from the oth.go file?

(apologies - I am very new to this!)

**Comment by retroplasma** [comment]
Hey there, did you set up a `config.json`? Which OS are you on?

**Comment by i-syme** [comment]
`config.json` is set up based on the shell script? Might try manually checking it. Running OSX 10.15.1

**Comment by retroplasma** [comment]
Yep, the shell script should do it. I tweaked it recently for 10.15.4. Hope it works for 10.15.1 as well.
